DOMAIN = "weatherlink"
PLATFORMS = ("air_quality", "sensor", "weather")


DECIMALS_DIRECTION = None
DECIMALS_HUMIDITY = None
DECIMALS_PM = 2
DECIMALS_PRESSURE = None
DECIMALS_PRESSURE_TREND = 1
DECIMALS_RADIATION = None
DECIMALS_RAIN_RATE = 1
DECIMALS_RAIN_VOLUME = 1
DECIMALS_SPEED = 1
DECIMALS_TEMPERATURE = 1
DECIMALS_UV = 1
DECIMALS_LEAF_WETNESS = None
DECIMALS_SOIL_MOISTURE = None
